apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-latency-component-onboarding-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: latency-component-onboarding
    interval: 1m
    rules:
    - alert: LatencyComponentOnboarding
      expr: |
        (
          (
            increase(redhat_appstudio_buildservice_component_onboarding_time_bucket{le="+Inf"}[5m])
            - ignoring(le)
            increase(redhat_appstudio_buildservice_component_onboarding_time_bucket{le="60"}[5m])
          ) / ignoring(le)
          increase(redhat_appstudio_buildservice_component_onboarding_time_bucket{le="+Inf"}[5m])
        ) > 0.10
      for: 1m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          Latency of component onboarding time exceeded
        description: >
          Time spent from the moment of Component creation till the initial simple build is submitted,
          if PaC provision is requested upon the Component creation, then till the provision finishes has been over
          60s for more than 10% of requests during the last 5 minutes on cluster
          {{ $labels.source_cluster }}
        alert_team_handle: <!subteam^S0500D143S8>
        team: build
        runbook_url: https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/build-service/latency_component_onboarding.md
